accessibilityJob: false
alwaysRunPostSteps: false
appium: null
betaFeature:
    setPartiallyCompletedAsCompleted: false
cacheDirectories:
    - node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
captureScreenRecordingForScenarios: false
codeDirectory: TestMu_Certification
collectLocalGitData: true
combineTasksInMatrixMode: false
concurrency: 2
cypress: false
differentialUpload:
    enabled: false
    forcedDisabled: false
    ttlHours: null
dynamicAllocation: false
env:
    FORM_PASSWORD: ${{.secrets.FORM_PASSWORD}}
    LT_ACCESS_KEY: ${{.secrets.LT_ACCESS_KEY}}
    LT_USERNAME: ${{.secrets.LT_USERNAME}}
    PLAYGROUND_BASE_URL: https://www.testmuai.com/selenium-playground/
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        artifacts: false
        autoGrantPermissions: false
        avoidAppLaunch: false
        customData: {}
        darkMode: false
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        enableBluetooth: false
        enableResultBundle: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: null
        isVirtualDevice: false
        language: ""
        locale: ""
        localhost: false
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        networkLogsOptions:
            captureContent: false
            excludeHosts: []
            includeHosts: []
        otherApps: []
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        smartUI: null
        testRemarks: false
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: ""
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalPost:
    commands: []
    completed: false
    disableEmail: false
    downloadArtifacts: false
    email:
        linkValidity: 0
        metaInfo: []
        templatePath: ""
        to: []
    mode: ""
    runson: ""
    shell: ""
    workingDirectory: ""
globalPre:
    commands: []
    completed: false
    location: ""
    maxRetries: 0
    mode: ""
    runson: ""
    shell: ""
    type: ""
    workingDirectory: ""
    yamlPath: null
jobID: cb58063a-d020-4054-abea-c2d11868f14f
key: '********'
localHTTPProxy: ""
ltOptions: {}
matrix:
    project:
        - win-chrome
        - linux-firefox
maxRetriesPreSteps: 0
mergeArtifacts: true
meta: {}
onpremEnv: ""
partialReports:
    type: html
    location: playwright-report
    frameworkName: playwright
    email:
        to: []
        metaInfo: []
        linkValidity: 0
    configPath: ""
    configPathURL: ""
platformConfig: null
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
pre:
    - npm ci
preDirectives:
    commands:
        - npm ci
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: 01M3SZA20S2GPZ25FV3WKZ8WZ2
    name: LambdaTest Default Project
    type: custom
projectpath: ""
regionConfig:
    storage:
        enabled: false
        name: ""
        platform: azure
        region: ""
    vm: []
report: true
runson: linux
runtime:
    addons: []
    language: node
    opts: {}
    version: "20"
slackChannel: ""
sourcePayload:
    verifySSL: true
sprofilePath: ""
storageType: ""
testDiscoveryResultV3: []
testSuites:
    - npm run test:cloud -- --project=${matrix.project}
testType: playwright
triggerMode: false
triggerSource: CLI
tunnelOpts:
    testsPerTunnel: 10
unzipPayload: false
uploadArtefacts:
    - email:
        linkValidity: 0
        metaInfo: []
        to: []
      name: Playwright-Execution
      path:
        - playwright-report/**
        - test-results/**
user: BrianAlbertoE
version: "0.1"
waitForArtefactsUpload: false
whiteLabelProductTag: ""
